configs:
  - id: b8c119e1-175c-3a9a-95af-e38411e6430f
    config:
      template: b8c119e1-175c-3a9a-95af-e38411e6430f.json
      skip: false
    type:
      settings:
        schema: builtin:container.monitoring-rule
        schemaVersion: 0.0.1
        scope: environment
  
  - id: bizopsapp
    config:
      name: "Partner PowerUp BizObs \\[customer-journey | Node.js\\] \\- POST /api/journey/start"
      template: bizopsapp.json
      skip: false
    type:
      settings:
        schema: builtin:bizevents.http.incoming
        scope: environment

  - id: SENSOR_DOTNET_BIZEVENTS_HTTP_INCOMING
    config:
      name: name
      template: SENSOR_DOTNET_BIZEVENTS_HTTP_INCOMING.json
      skip: false
    type:
      settings:
        schema: builtin:oneagent.features
        scope: environment

  - id: SENSOR_JAVA_BIZEVENTS_HTTP_INCOMING
    config:
      name: name
      template: SENSOR_JAVA_BIZEVENTS_HTTP_INCOMING.json
      skip: false
    type:
      settings:
        schema: builtin:oneagent.features
        scope: environment

  - id: capture-rules
    type:
      openpipeline:
        kind: bizevents
    config:
      name: Revenue
      template: capturerules.json
      skip: false
