#
# Partner PowerUp BizObs - ACE-BOX Use Case (Final Optimized Version)
# Uses streamlined startup script designed specifically for ACE-BOX
# Command: ace enable https://github.com/lawrobar90/ace-box-ext-hot-partner-powerup-bizobs.git --local
#

---
- debug:
    msg: "🚀 ACE-BOX: Deploying Partner PowerUp BizObs (Optimized)"

# Set application variables
- set_fact:
    bizobs_repo_url: "https://github.com/lawrobar90/Partner-PowerUp-BizObs-App.git"
    bizobs_app_dir: "/home/{{ ace_box_user | default('dt_training') }}/Partner-PowerUp-BizObs-App"
    bizobs_domain: "bizobs.{{ ingress_domain }}"

# 
# STEP 1: Dynatrace Authentication (ACE-BOX curated role)
#
- include_role:
    name: dt-access-token
  vars:
    access_token_var_name: "monaco_cleanup_api_token"
    access_token_scope:
      [
        "slo.read", "slo.write", "CaptureRequestData", "credentialVault.read", 
        "credentialVault.write", "DataExport", "DataPrivacy", "ExternalSyntheticIntegration",
        "ReadConfig", "WriteConfig", "events.ingest", "settings.read", "settings.write",
        "metrics.ingest", "openTelemetryTrace.ingest", "logs.ingest"
      ]

#
# STEP 2: Core Infrastructure (ACE-BOX curated roles)
#
- include_role:
    name: "microk8s"

- include_role:
    name: "nodejs"

# 
# STEP 3: Application Deployment (Streamlined)
#
- name: Clone Partner PowerUp BizObs repository
  ansible.builtin.git:
    repo: "{{ bizobs_repo_url }}"
    dest: "{{ bizobs_app_dir }}"
    version: "main"
    force: yes
  become_user: "{{ ace_box_user | default('dt_training') }}"

- name: Install application dependencies
  ansible.builtin.command:
    cmd: npm install --production
    chdir: "{{ bizobs_app_dir }}"
  become_user: "{{ ace_box_user | default('dt_training') }}"

- name: Copy ACE-BOX optimized startup script
  ansible.builtin.copy:
    src: start-server-ace-optimized.sh
    dest: "{{ bizobs_app_dir }}/start-server.sh"
    mode: '0755'

- name: Start BizObs application (ACE-BOX optimized)
  ansible.builtin.shell: /bin/sh ./start-server.sh
  become: true
  args:
    chdir: "{{ bizobs_app_dir }}"
  async: 30
  poll: 0

- name: Wait for application startup
  ansible.builtin.wait_for:
    port: 8080
    host: localhost
    delay: 5
    timeout: 45

#
# STEP 4: Observability & Monitoring (ACE-BOX curated roles)
#
- include_role:
    name: "dt-oneagent-classic"

- include_role:
    name: "monaco-v2"

#
# STEP 5: Team Collaboration (ACE-BOX curated roles)
#
- include_role:
    name: "mattermost"

- include_role:
    name: "dashboard"

#
# STEP 6: External Access (Kubernetes ingress)
#
- name: Create BizObs Kubernetes service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: bizobs-service
        namespace: default
        labels:
          app: bizobs
          component: partner-powerup
      spec:
        type: ExternalName
        externalName: localhost
        ports:
        - port: 8080
          targetPort: 8080
          name: http

- name: Create BizObs ingress for external access
  kubernetes.core.k8s:
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: bizobs-ingress
        namespace: default
        labels:
          app: bizobs
          component: partner-powerup
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      spec:
        ingressClassName: "{{ ingress_class | default('nginx') }}"
        rules:
        - host: "{{ bizobs_domain }}"
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: bizobs-service
                  port:
                    number: 8080

# Final verification and success message
- name: Verify application health
  ansible.builtin.uri:
    url: "http://localhost:8080/health"
    method: GET
    status_code: 200
  register: health_check
  retries: 3
  delay: 5

- debug:
    msg: |
      ✅ Partner PowerUp BizObs deployed successfully via ACE-BOX!
      
      🔗 Access URLs:
      - BizObs App: {{ ingress_protocol | default('http') }}://{{ bizobs_domain }}/
      - Dashboard: {{ ingress_protocol | default('http') }}://dashboard.{{ ingress_domain }}/
      - Mattermost: {{ ingress_protocol | default('http') }}://mattermost.{{ ingress_domain }}/
      
      🎯 Health Check: {{ health_check.status }} - {{ health_check.msg | default('OK') }}
      
      🎭 Demo Features Ready:
      - Customer Journey Simulation (Insurance, Retail, Tech, Banking)
      - Multi-persona Load Generation (Karen, Raj, Alex, Sophia)
      - Dynatrace Integration with Business Events
      - Real-time Observability Dashboard
      - Dynamic Service Mesh Creation
      
      🚀 Ready for: ace enable https://github.com/lawrobar90/ace-box-ext-hot-partner-powerup-bizobs.git --local