#
# Partner PowerUp BizObs - ACE-BOX Use Case
# Optimized for: ace enable https://github.com/lawrobar90/ace-box-ext-hot-partner-powerup-bizobs.git --local
# Follows the exact pattern your colleague showed
#

---
- debug:
    msg: "🚀 Deploying Partner PowerUp BizObs Application via ACE Enable!"

# Set BizObs application variables (following ACE-BOX conventions)
- set_fact:
    bizobs_repo_url: "https://github.com/lawrobar90/Partner-PowerUp-BizObs-App.git"
    bizobs_app_dir: "/home/{{ ace_box_user | default('dt_training') }}/Partner-PowerUp-BizObs-App"
    bizobs_domain: "bizobs.{{ ingress_domain }}"

# 
# STEP 1: Dynatrace Authentication (ACE-BOX curated role)
#
- include_role:
    name: dt-access-token
  vars:
    access_token_var_name: "monaco_cleanup_api_token"
    access_token_scope:
      [
        "slo.read", "slo.write", "CaptureRequestData", "credentialVault.read", 
        "credentialVault.write", "DataExport", "DataPrivacy", "ExternalSyntheticIntegration",
        "ReadConfig", "WriteConfig", "events.ingest", "settings.read", "settings.write",
        "metrics.ingest", "openTelemetryTrace.ingest", "logs.ingest"
      ]

#
# STEP 2: Infrastructure (ACE-BOX curated roles)
#
- include_role:
    name: "microk8s"

- include_role:
    name: "nodejs"

# 
# STEP 3: Download repo, install dependencies, start application
# (Following your colleague's exact pattern)
#
- name: Clone Partner PowerUp BizObs repository
  ansible.builtin.git:
    repo: "{{ bizobs_repo_url }}"
    dest: "{{ bizobs_app_dir }}"
    version: "main"
    force: yes
  become_user: "{{ ace_box_user | default('dt_training') }}"

- name: Install npm dependencies
  ansible.builtin.command:
    cmd: npm install --production
    chdir: "{{ bizobs_app_dir }}"
  become_user: "{{ ace_box_user | default('dt_training') }}"

- name: Start Application (using your colleague's exact pattern)
  ansible.builtin.shell: /bin/sh ./start-server.sh
  become: true
  args:
    chdir: "{{ bizobs_app_dir }}"
  async: 30
  poll: 0

- name: Wait for BizObs to start
  ansible.builtin.wait_for:
    port: 8080
    host: localhost
    delay: 10
    timeout: 60

#
# STEP 4: Dynatrace Integration (ACE-BOX curated roles)
#
- include_role:
    name: "dt-oneagent-classic"

- include_role:
    name: "monaco-v2"

#
# STEP 5: Team Tools (ACE-BOX curated roles)
#
- include_role:
    name: "mattermost"

- include_role:
    name: "dashboard"

#
# STEP 6: External Access (Kubernetes ingress)
#
- name: Create BizObs Kubernetes service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: bizobs-service
        namespace: default
      spec:
        type: ExternalName
        externalName: localhost
        ports:
        - port: 8080
          targetPort: 8080

- name: Create BizObs ingress for external access
  kubernetes.core.k8s:
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: bizobs-ingress
        namespace: default
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
      spec:
        ingressClassName: "{{ ingress_class | default('nginx') }}"
        rules:
        - host: "{{ bizobs_domain }}"
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: bizobs-service
                  port:
                    number: 8080

# Success message
- debug:
    msg: |
      ✅ Partner PowerUp BizObs deployed successfully via ACE Enable!
      
      🔗 Access URLs:
      - BizObs App: http://{{ bizobs_domain }}/
      - Dashboard: http://dashboard.{{ ingress_domain }}/
      - Mattermost: http://mattermost.{{ ingress_domain }}/
      - Health: http://{{ bizobs_domain }}/api/health
      
      🎯 Ready for ace enable command:
      ace enable https://github.com/lawrobar90/ace-box-ext-hot-partner-powerup-bizobs.git --local